import { colors, typography, spacing, radius, shadows, gradients } from './src/theme';
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Blue scale
        blue1: colors.blue.blue1,
        blue2: colors.blue.blue2,
        blue3: colors.blue.blue3,
        blue4: colors.blue.blue4,
        blue5: colors.blue.blue5,
        blue6: colors.blue.blue6,
        blue7: colors.blue.blue7,
        blue8: colors.blue.blue8,
        blue9: colors.blue.blue9,
        blue10: colors.blue.blue10,
        blue11: colors.blue.blue11,
        blue12: colors.blue.blue12,
        
        // Slate scale
        slate1: colors.slate.slate1,
        slate2: colors.slate.slate2,
        slate3: colors.slate.slate3,
        slate4: colors.slate.slate4,
        slate5: colors.slate.slate5,
        slate6: colors.slate.slate6,
        slate7: colors.slate.slate7,
        slate8: colors.slate.slate8,
        slate9: colors.slate.slate9,
        slate10: colors.slate.slate10,
        slate11: colors.slate.slate11,
        slate12: colors.slate.slate12,
        
        // Purple scale
        purple1: colors.purple.purple1,
        purple2: colors.purple.purple2,
        purple3: colors.purple.purple3,
        purple4: colors.purple.purple4,
        purple5: colors.purple.purple5,
        purple6: colors.purple.purple6,
        purple7: colors.purple.purple7,
        purple8: colors.purple.purple8,
        purple9: colors.purple.purple9,
        purple10: colors.purple.purple10,
        purple11: colors.purple.purple11,
        purple12: colors.purple.purple12,
        
        // Green scale
        green1: colors.green.green1,
        green2: colors.green.green2,
        green3: colors.green.green3,
        green4: colors.green.green4,
        green5: colors.green.green5,
        green6: colors.green.green6,
        green7: colors.green.green7,
        green8: colors.green.green8,
        green9: colors.green.green9,
        green10: colors.green.green10,
        green11: colors.green.green11,
        green12: colors.green.green12,
        
        // Red scale
        red1: colors.red.red1,
        red2: colors.red.red2,
        red3: colors.red.red3,
        red4: colors.red.red4,
        red5: colors.red.red5,
        red6: colors.red.red6,
        red7: colors.red.red7,
        red8: colors.red.red8,
        red9: colors.red.red9,
        red10: colors.red.red10,
        red11: colors.red.red11,
        red12: colors.red.red12,

        // Yellow scale
        yellow1: colors.yellow.yellow1,
        yellow2: colors.yellow.yellow2,
        yellow3: colors.yellow.yellow3,
        yellow4: colors.yellow.yellow4,
        yellow5: colors.yellow.yellow5,
        yellow6: colors.yellow.yellow6,
        yellow7: colors.yellow.yellow7,
        yellow8: colors.yellow.yellow8,
        yellow9: colors.yellow.yellow9,
        yellow10: colors.yellow.yellow10,
        yellow11: colors.yellow.yellow11,
        yellow12: colors.yellow.yellow12,

        // Orange scale
        orange1: colors.orange.orange1,
        orange2: colors.orange.orange2,
        orange3: colors.orange.orange3,
        orange4: colors.orange.orange4,
        orange5: colors.orange.orange5,
        orange6: colors.orange.orange6,
        orange7: colors.orange.orange7,
        orange8: colors.orange.orange8,
        orange9: colors.orange.orange9,
        orange10: colors.orange.orange10,
        orange11: colors.orange.orange11,
        orange12: colors.orange.orange12,

        // Pink scale
        pink1: colors.pink.pink1,
        pink2: colors.pink.pink2,
        pink3: colors.pink.pink3,
        pink4: colors.pink.pink4,
        pink5: colors.pink.pink5,
        pink6: colors.pink.pink6,
        pink7: colors.pink.pink7,
        pink8: colors.pink.pink8,
        pink9: colors.pink.pink9,
        pink10: colors.pink.pink10,
        pink11: colors.pink.pink11,
        pink12: colors.pink.pink12,

        // Cyan scale
        cyan1: colors.cyan.cyan1,
        cyan2: colors.cyan.cyan2,
        cyan3: colors.cyan.cyan3,
        cyan4: colors.cyan.cyan4,
        cyan5: colors.cyan.cyan5,
        cyan6: colors.cyan.cyan6,
        cyan7: colors.cyan.cyan7,
        cyan8: colors.cyan.cyan8,
        cyan9: colors.cyan.cyan9,
        cyan10: colors.cyan.cyan10,
        cyan11: colors.cyan.cyan11,
        cyan12: colors.cyan.cyan12,

        // Semantic colors
        primary: colors.semantic.primary,
        'primary-hover': colors.semantic.primaryHover,
        'primary-subtle': colors.semantic.primarySubtle,
        secondary: colors.semantic.secondary,
        success: colors.semantic.success,
        error: colors.semantic.error,
        warning: colors.semantic.warning,

        // Brand colors
        white: colors.brand.white,
        black: colors.brand.black,
        'lite-dark': colors.brand.liteDark,
        'light-green': colors.brand.lightGreenColor,
        'deep-pink': colors.brand.deepPink,
        'jet-black': colors.brand.jetBlack,
        'only-green': colors.brand.onlyGreen,
        'basic-purple': colors.brand.basicPurple,
        'aqua-mint': colors.brand.aquaMint,
        'deep-midnight': colors.brand.deepMidnight,
        'sky-blue': colors.brand.skyBlue,
        'lavender-pink': colors.brand.lavenderPink,
        'sunflower-yellow': colors.brand.sunflowerYellow,
        'charcoal-black': colors.brand.charcoalBlack,
        'neon-green': colors.brand.neonGreen,
        'royal-purple': colors.brand.royalPurple,
        'medium-gray': colors.brand.mediumGray,
        'electric-purple': colors.brand.electricPurple,
        'vibrant-orange': colors.brand.vibrantOrange,
        'golden-yellow': colors.brand.goldenYellow,
        'airdrop-info': colors.brand.airdropInfo,
        'airdrop-task': colors.brand.airdropTask,
        'red-light': colors.brand.redLight,
      },

      fontSize: typography.fontSize,
      fontWeight: typography.fontWeight,
      spacing: spacing,
      borderRadius: radius,
      boxShadow: shadows,
      backgroundImage: gradients,
    },
  },
  plugins: [],
};

export default config;